language: node_js
node_js:
  - v9.4.0
cache:
  directories:
    - node_modules
  yarn: true
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
notifications:
  slack: 'kleros:Ub8n81EgKJ3iRrMDyWyQIVJp'
